// Mocks generated by Mockito 5.4.6 from annotations
// in lapor_kerja/test/domain/usecases/task/add_task/add_task_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lapor_kerja/core/utils/result.dart' as _i5;
import 'package:lapor_kerja/domain/entities/task_entity.dart' as _i4;
import 'package:lapor_kerja/domain/repositories/task_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i2.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.TaskEntity>> watchAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllTasks, []),
            returnValue: _i3.Stream<List<_i4.TaskEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.TaskEntity>>);

  @override
  _i3.Stream<List<_i4.TaskEntity>> watchTasksForProject(int? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTasksForProject, [projectId]),
            returnValue: _i3.Stream<List<_i4.TaskEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.TaskEntity>>);

  @override
  _i3.Future<_i5.Result<_i4.TaskEntity>> getTaskById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue: _i3.Future<_i5.Result<_i4.TaskEntity>>.value(
              _i6.dummyValue<_i5.Result<_i4.TaskEntity>>(
                this,
                Invocation.method(#getTaskById, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.TaskEntity>>);

  @override
  _i3.Future<_i5.Result<void>> createTask(_i4.TaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#createTask, [task]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> updateTask(_i4.TaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateTask, [task]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> softDeleteTask(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteTask, [id]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#softDeleteTask, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<List<_i4.TaskEntity>>> getUnsyncedTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedTasks, []),
            returnValue: _i3.Future<_i5.Result<List<_i4.TaskEntity>>>.value(
              _i6.dummyValue<_i5.Result<List<_i4.TaskEntity>>>(
                this,
                Invocation.method(#getUnsyncedTasks, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<List<_i4.TaskEntity>>>);

  @override
  _i3.Future<_i5.Result<void>> markTaskAsSynced(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#markTaskAsSynced, [id]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#markTaskAsSynced, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepositoryForAdd extends _i1.Mock implements _i2.TaskRepository {
  MockTaskRepositoryForAdd() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.TaskEntity>> watchAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllTasks, []),
            returnValue: _i3.Stream<List<_i4.TaskEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.TaskEntity>>);

  @override
  _i3.Stream<List<_i4.TaskEntity>> watchTasksForProject(int? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTasksForProject, [projectId]),
            returnValue: _i3.Stream<List<_i4.TaskEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.TaskEntity>>);

  @override
  _i3.Future<_i5.Result<_i4.TaskEntity>> getTaskById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue: _i3.Future<_i5.Result<_i4.TaskEntity>>.value(
              _i6.dummyValue<_i5.Result<_i4.TaskEntity>>(
                this,
                Invocation.method(#getTaskById, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.TaskEntity>>);

  @override
  _i3.Future<_i5.Result<void>> createTask(_i4.TaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#createTask, [task]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#createTask, [task]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> updateTask(_i4.TaskEntity? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateTask, [task]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> softDeleteTask(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteTask, [id]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#softDeleteTask, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<List<_i4.TaskEntity>>> getUnsyncedTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedTasks, []),
            returnValue: _i3.Future<_i5.Result<List<_i4.TaskEntity>>>.value(
              _i6.dummyValue<_i5.Result<List<_i4.TaskEntity>>>(
                this,
                Invocation.method(#getUnsyncedTasks, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<List<_i4.TaskEntity>>>);

  @override
  _i3.Future<_i5.Result<void>> markTaskAsSynced(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#markTaskAsSynced, [id]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#markTaskAsSynced, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);
}
