// Mocks generated by Mockito 5.4.6 from annotations
// in lapor_kerja/test/domain/usecases/income/update_income/update_income_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lapor_kerja/core/utils/result.dart' as _i5;
import 'package:lapor_kerja/domain/entities/income_entity.dart' as _i4;
import 'package:lapor_kerja/domain/repositories/income_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IncomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncomeRepository extends _i1.Mock implements _i2.IncomeRepository {
  MockIncomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.IncomeEntity>> watchAllIncomes() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllIncomes, []),
            returnValue: _i3.Stream<List<_i4.IncomeEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.IncomeEntity>>);

  @override
  _i3.Stream<List<_i4.IncomeEntity>> watchIncomesForProject(int? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#watchIncomesForProject, [projectId]),
            returnValue: _i3.Stream<List<_i4.IncomeEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.IncomeEntity>>);

  @override
  _i3.Future<_i5.Result<_i4.IncomeEntity>> getIncomeById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getIncomeById, [id]),
            returnValue: _i3.Future<_i5.Result<_i4.IncomeEntity>>.value(
              _i6.dummyValue<_i5.Result<_i4.IncomeEntity>>(
                this,
                Invocation.method(#getIncomeById, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.IncomeEntity>>);

  @override
  _i3.Future<_i5.Result<void>> createIncome(_i4.IncomeEntity? income) =>
      (super.noSuchMethod(
            Invocation.method(#createIncome, [income]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#createIncome, [income]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> updateIncome(_i4.IncomeEntity? income) =>
      (super.noSuchMethod(
            Invocation.method(#updateIncome, [income]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateIncome, [income]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> softDeleteIncome(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteIncome, [id]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#softDeleteIncome, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<List<_i4.IncomeEntity>>> getUnsyncedIncomes() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedIncomes, []),
            returnValue: _i3.Future<_i5.Result<List<_i4.IncomeEntity>>>.value(
              _i6.dummyValue<_i5.Result<List<_i4.IncomeEntity>>>(
                this,
                Invocation.method(#getUnsyncedIncomes, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<List<_i4.IncomeEntity>>>);

  @override
  _i3.Future<_i5.Result<void>> markIncomeAsSynced(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#markIncomeAsSynced, [id]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#markIncomeAsSynced, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);
}

/// A class which mocks [IncomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncomeRepositoryForUpdate extends _i1.Mock
    implements _i2.IncomeRepository {
  MockIncomeRepositoryForUpdate() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.IncomeEntity>> watchAllIncomes() =>
      (super.noSuchMethod(
            Invocation.method(#watchAllIncomes, []),
            returnValue: _i3.Stream<List<_i4.IncomeEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.IncomeEntity>>);

  @override
  _i3.Stream<List<_i4.IncomeEntity>> watchIncomesForProject(int? projectId) =>
      (super.noSuchMethod(
            Invocation.method(#watchIncomesForProject, [projectId]),
            returnValue: _i3.Stream<List<_i4.IncomeEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.IncomeEntity>>);

  @override
  _i3.Future<_i5.Result<_i4.IncomeEntity>> getIncomeById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getIncomeById, [id]),
            returnValue: _i3.Future<_i5.Result<_i4.IncomeEntity>>.value(
              _i6.dummyValue<_i5.Result<_i4.IncomeEntity>>(
                this,
                Invocation.method(#getIncomeById, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<_i4.IncomeEntity>>);

  @override
  _i3.Future<_i5.Result<void>> createIncome(_i4.IncomeEntity? income) =>
      (super.noSuchMethod(
            Invocation.method(#createIncome, [income]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#createIncome, [income]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> updateIncome(_i4.IncomeEntity? income) =>
      (super.noSuchMethod(
            Invocation.method(#updateIncome, [income]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#updateIncome, [income]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<void>> softDeleteIncome(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteIncome, [id]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#softDeleteIncome, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);

  @override
  _i3.Future<_i5.Result<List<_i4.IncomeEntity>>> getUnsyncedIncomes() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedIncomes, []),
            returnValue: _i3.Future<_i5.Result<List<_i4.IncomeEntity>>>.value(
              _i6.dummyValue<_i5.Result<List<_i4.IncomeEntity>>>(
                this,
                Invocation.method(#getUnsyncedIncomes, []),
              ),
            ),
          )
          as _i3.Future<_i5.Result<List<_i4.IncomeEntity>>>);

  @override
  _i3.Future<_i5.Result<void>> markIncomeAsSynced(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#markIncomeAsSynced, [id]),
            returnValue: _i3.Future<_i5.Result<void>>.value(
              _i6.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#markIncomeAsSynced, [id]),
              ),
            ),
          )
          as _i3.Future<_i5.Result<void>>);
}
