// Mocks generated by Mockito 5.4.6 from annotations
// in lapor_kerja/test/domain/repositories/time_entry_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lapor_kerja/domain/entities/time_entry_entity.dart' as _i4;
import 'package:lapor_kerja/domain/repositories/time_entry_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TimeEntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimeEntryRepository extends _i1.Mock
    implements _i2.TimeEntryRepository {
  MockTimeEntryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.TimeEntryEntity>> watchTimeEntriesForTask(int? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTimeEntriesForTask, [taskId]),
            returnValue: _i3.Stream<List<_i4.TimeEntryEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.TimeEntryEntity>>);

  @override
  _i3.Future<_i4.TimeEntryEntity?> getTimeEntryById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeEntryById, [id]),
            returnValue: _i3.Future<_i4.TimeEntryEntity?>.value(),
          )
          as _i3.Future<_i4.TimeEntryEntity?>);

  @override
  _i3.Future<void> createTimeEntry(_i4.TimeEntryEntity? timeEntry) =>
      (super.noSuchMethod(
            Invocation.method(#createTimeEntry, [timeEntry]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTimeEntry(_i4.TimeEntryEntity? timeEntry) =>
      (super.noSuchMethod(
            Invocation.method(#updateTimeEntry, [timeEntry]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> softDeleteTimeEntry(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteTimeEntry, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.TimeEntryEntity>> getUnsyncedTimeEntries() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedTimeEntries, []),
            returnValue: _i3.Future<List<_i4.TimeEntryEntity>>.value(
              <_i4.TimeEntryEntity>[],
            ),
          )
          as _i3.Future<List<_i4.TimeEntryEntity>>);

  @override
  _i3.Future<void> markTimeEntryAsSynced(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#markTimeEntryAsSynced, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
